### ISSUE TITLE
Installation with E3DC S10 (SunSpec mode) does not work

### ISSUE THREAD

**Issue by SaschaHenning** [CJNE/ha-sunspec#62]
## Version of the custom_component
`0.0.18`

## Configuration

Not available since installation of intregration does not work.

## Describe the bug

System:
- E3DC S10 ( https://www.e3dc.com )
- Modbus Mode: Sunspec ( http://sunspec.org/wp-content/uploads/2016/02/SunSpec-Information-Model-Reference.xlsx )
- Configuration: https://www.loxwiki.eu/download/attachments/9339566/ModuBus-Dokumentation_2016-08-05.pdf?version=1&modificationDate=1471507657000&api=v2 -> see chapter 3.2 for sunspec config

Error occurs when trying to add the integration on "/config/integrations". It cannot install due to `Failed to connect to host 192.168.0.245:502 slave 1 - Repeating group count not consistent with model length for model 803,model repeating len = 6, model repeating group len = 32`(see logs below)

*Did anyone successfully use this integration for an E3DC device?*

It works fine when I use the modbus integration for direct register access. Here a part of my configuration (for details compare with excel above):

```yaml
modbus:
  - name: E3DC
    type: tcp
    host: 192.168.0.245
    port: 502
    sensors:
      - name: e3dc_meter_home_incoming
        unit_of_measurement: kWh
        address: 40248 #40203+46-1
        slave: 1
        device_class: energy
        count: 2
        scan_interval: 15
        data_type: uint32
        scale: 0.001
        precision: 2
      - name: e3dc_meter_home_exporting
        unit_of_measurement: kWh
        address: 40240 #40203+38-1
        slave: 1
        device_class: energy
        count: 2
        scan_interval: 15
        data_type: uint32
        scale: 0.001
        precision: 2
...
```

## Debug log

```text
2021-11-13 21:03:09 DEBUG (MainThread) [custom_components.sunspec] New SunspecApi Client
2021-11-13 21:03:09 DEBUG (SyncWorker_1) [custom_components.sunspec] Client connect to IP 192.168.0.245 port 502 slave id 0 using timeout 60
2021-11-13 21:03:09 DEBUG (SyncWorker_1) [custom_components.sunspec] Client connected, perform initial scan
2021-11-13 21:03:09 ERROR (MainThread) [custom_components.sunspec] Failed to connect to host 192.168.0.245:502 slave 1 - Repeating group count not consistent with model length for model 803,model repeating len = 6, model repeating group len = 32
```
