### ISSUE TITLE
Sensor is count wrong direction.

### ISSUE THREAD

**Issue by mbuhansen** [CJNE/ha-sunspec#88]
## Version of the custom_component
v0.0.20

## Configuration

```yaml
Add your logs here.

state_class: total_increasing
integration: sunspec
sunspec_key: TotWhExp
label: Total Watt-hours Exported
unit_of_measurement: Wh
device_class: energy
icon: mdi:solar-panel
friendly_name: Ac_meter Total Watt-hours Exported

## Describe the bug

A clear and concise description of what the bug is.

Hi i use this sunspec intregration, i have problem with one sensor total watt hours exported, the value in HA is count down, In my kostal smart meter the value is count up.
When i add the sensor to energy dashboard in HA it can't rister the feed in power correct because the sensor is count down the value. 
Is it possible to chenge so the value is count UP.



Add your logs here.

```
